name: Runtime Check

on:
  pull_request:
  push:
    branches: [ main, master, feat/** ]

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Runtime check
        run: node scripts/runtime-check.js dist index.html runtime-report.json
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: runtime-report
          path: runtime-report.json
      - name: Playwright smoke tests
        run: npx playwright test -c playwright.config.js
